### ISSUE TITLE
`createMultipleNFT` is missing in v2

### ISSUE THREAD

**Issue by vikiival** [kodadot/packages#126]
V1 subpackage of minimark has something called `createMultipleNFT` and we miss that to implement stuff in our NFT gallery

```ts
import {
  createMultipleNFT,
} from '@kodadot1/minimark/v1'
```

## Task in V2 subpackage
1. create function called `createMultipleItem` that will have **SAME** API as `createMultipleNFT`
2. copy most of the stuff from `createMultipleNFT`
3. replace `createInteraction` from v1 to v2
4. fix the changes

## Output

```ts
import {
  createMultipleItem,
} from '@kodadot1/minimark/v2'
```

**Comment by Matehoo** [comment]
Inside new `createMultipleItem` in v2 should I use `createNFT` in v2? 
WDYM by replace `createInteraction` from v1 to v2 ? `createInteraction` is implemented in both versions

**Comment by vikiival** [comment]
> Inside new createMultipleItem in v2 should I use createNFT in v2?

Yes

**Comment by Matehoo** [comment]
Is the missing `caller` attribute in v2 correct? Shouldnt the nft has `currentOwner` set as a `caller`(same as in v1)?

**Comment by vikiival** [comment]
> Is the missing caller attribute in v2 correct?

Yup we calculate it on the indexer 

https://github.com/kodadot/rubick/blob/63945cde2348bc8a5ec9d24af4d3bf8229ce3a41/src/mappings/v2/mint.ts#L69

But for the sake of the API we can add it
