### ISSUE TITLE
get single ipfs provider

### ISSUE THREAD

**Issue by preschian** [kodadot/packages#182]
ref:
- https://github.com/kodadot/workers/pull/206#discussion_r1399163405
- https://github.com/kodadot/workers/pull/206#discussion_r1399163021

```js
return purifySingle(ipfs, 'kodadot_beta')
```

```js
getProvider()
```

**Comment by vikiival** [comment]
Added in 55b3acfd6cb3edb9f0daee54ce9effe8e8cfd279
