### ISSUE TITLE
Cant obtain metadata with $obtain in Nuxt 3

### ISSUE THREAD

**Issue by brano-hozza** [kodadot/packages#192]
Hey I was trying to use minipfs $obtain functionality to get metadata from [here](https://nftdata.parallelnft.com/api/parallel-alpha/ipfs/QmXfnQX6Ej3Q12BiBhJKWTYGzZC9bwASrQjHB9kJjaVDG9) but I got empty response:
![image](https://github.com/kodadot/packages/assets/64609060/48180789-4154-4228-9eda-ed2436949f01)
![image](https://github.com/kodadot/packages/assets/64609060/339d506b-0ba9-4d55-b9b4-bc8ead72f255)
Here is the code to that:
```ts
if (nftData.value?.uri) {
    console.log(nftData.value?.uri);
   //uri: https://nftdata.parallelnft.com/api/parallel-alpha/ipfs/QmXfnQX6Ej3Q12BiBhJKWTYGzZC9bwASrQjHB9kJjaVDG9
    const data = await $obtain<{ image: string }>(nftData.value.uri);
    sources.value = [data.image];
  }
 ```
It is failing as `data` is `undefined`

**Comment by vikiival** [comment]
```ts
try {
  const url = 'https://nftdata.parallelnft.com/api/parallel-alpha/ipfs/QmXfnQX6Ej3Q12BiBhJKWTYGzZC9bwASrQjHB9kJjaVDG9'
  const x = await $obtain(url)
  console.log(x)
} catch (e) {
  console.log(e)
}
```

```js
{
  name: 'Neutron Bomb',
  description: 'When negotiation fails, the Marcolian simply wipe the slate clean, and build in their image.',
  image: 'https://nftmedia.parallelnft.com/parallel-alpha/QmZ2fbPSB9vKxZC3CGc5DMyBjuvtQVnrGcjv1U2ZY3Rboo/image.png',
  external_url: 'https://rarible.com/token/0x76be3b62873462d2142405439777e971754e8e77:11',
  attributes: [
    { key: 'Rarity', trait_type: 'Rarity', value: 'Legendary' },
    { key: 'Class', trait_type: 'Class', value: 'First Edition' },
    { key: 'Artist', trait_type: 'Artist', value: 'Oscar Mar' },
    { key: 'Parallel', trait_type: 'Parallel', value: 'Marcolian' }
  ],
  token_id: 11
}
```

@brano-hozza can you make some minimal codesandbox for this?

**Comment by brano-hozza** [comment]
@vikiival tried that and it's still undefined

**Comment by vikiival** [comment]
> @vikiival tried that and it's still undefined

Can you please share the code sandbox?

**Comment by brano-hozza** [comment]
> > @vikiival tried that and it's still undefined
> 
> Can you please share the code sandbox?

https://codesandbox.io/p/devbox/wizardly-danilo-qwph3w

**Comment by vikiival** [comment]
@brano-hozza have you managed to fix it?
If so can u describe how and we can close :)
