### ISSUE TITLE
Api spawns too many websockets

### ISSUE THREAD

**Issue by vikiival** [kodadot/packages#36]
https://github.com/kodadot/nft-gallery/pull/3500#issuecomment-1191270556
![180182338-cd3df53d-5fcb-48a5-918f-b5e5721bac45](https://user-images.githubusercontent.com/22471030/180785440-51af3745-fc55-4696-9d3c-6576bef9ae7b.png)

Basically app runs out of the free websocket

**Comment by vikiival** [comment]
https://stackoverflow.com/questions/69008820/websocket-connection-error-insufficient-resources

**Comment by yangwao** [comment]
> Instead, wrap the instantiation of WebSockets with a useEffect (such that it only triggers once, and is disconnected when the component is unmounted).

Are we using it wrong?
