### ISSUE TITLE
sub-api teleport ready 

### ISSUE THREAD

**Issue by yangwao** [kodadot/packages#78]
> I'm afraid that it could not use sub-api. Because If I want to teleport tokens from Kusama, I need to use ApiPromise of kusama. On the other hand, I would use ApiPromise of basilisk.

> And sub-api would only return the API endpoint according to the current prefix. 👀

https://github.com/kodadot/nft-gallery/pull/4297#discussion_r1029395842

**Comment by vikiival** [comment]
It's done since the beginning of sub-api :) 
https://github.com/kodadot/packages/tree/main/sub-api#whats-in-the-box
